### ISSUE TITLE
Generate simple DDL based off annotated POJO

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [dieselpoint/norm#6]
Do you think that's within norm's scope? Or is this getting into crazy town?

**Comment by ccleve** [comment]
You could do it, but you might be better off doing something database-specific. Here's an example:

http://stackoverflow.com/questions/1537951/generate-table-ddl-via-query-on-mysql-and-sql-server

Norm wouldn't do a very good job because all it has is the metadata associated with a pojo. It doesn't know about indexes, foreign keys, etc.

Nevertheless, it would be possible to generate a (very) primitive "create table" command from a pojo class. Is this valuable?

**Comment by Ghoughpteighbteau** [comment]
I don't rightly know if it's globally useful, it fit's my use case where we have lots of servers with simple objects and we just use the database as a simple data store. We wire our associations up in the server, not in the database. That said, I would need indexes. 

I don't have very much against the JPA standard, just JPQL :P

I think the problem is that if you made norm understand JPA, people might get the sense that it does the crazy town things like cascading or eager/lazy fetching or whatever else inevitably surfaces in quagmire.

**Comment by ccleve** [comment]
I did implement db.createTable(MyPojo.class). It's primitive, but it works. Doing a new release shortly.
